### ISSUE TITLE
Description for marching through the states?

### ISSUE THREAD

**Issue by bmhowe34** [realead/qwixxmaster#1]
I was wondering if you might be willing to discuss your algorithm about marching through the states while forming your optimal single player "perfect strategy". When I implemented my own algorithm (a few years ago, but apparently after your code was posted here), I came up with an expected score of 115.4831, which is just slightly less than what you claim is your expected score under the optimal single player strategy (115.911). While our numbers match pretty well, I'm curious if I can track down the discrepancy. (Perhaps we have a different interpretation of the rules?) For what it's worth, I discussed my approach here: https://drive.google.com/file/d/0B0E4VFlFjnCuME9sZGhrbGRIWXc/view

My approach was later optimized after a reddit user helped me realize some of the redundant states. Once that was accounted for, my single player strategy optimization program runs in about 90 minutes. I got the same answer [115.4831] both before and after my optimizations, so I imagine the optimizations aren't particularly relevant to the exact answer.

**Comment by bmhowe34** [comment]
I think I found the difference in our interpretation of the Qwixx rules. It is near this spot in the code:

https://github.com/realead/qwixxmaster/blob/489620c3a5da1e9514b6dd8e4aff4d7af1845793/src/Evaluator.cpp#L146

You are allowing the player to possibly to execute `evaluate_without_whites()` even if the `if(cur.take(color, roll[4]+roll[5]))` ended the game two lines earlier. I guess that boils down to whether or not you interpret the rules as ending the game _right away_ once two colors are locked or whether or not you let the player complete their 2nd (optional) move during their turn even if their first move resulted in having two locked rows. If I make a similar change to my code, I get 115.91081 for the expected value at the start of the game, which matches your number.

**Comment by realead** [comment]
@bmhowe34 It is very kind of you to call this bug "different interpretation of rules"! I've just missed this point. 

Actually, I'm quite impressed with the performance of your implementation, mine seems to be about order of magnitude slower. I understood, that 2/3 of mine states are just empty but didn't care much, because they would not be touched anyway - maybe this was wrong. But I didn't profile my program, so I don't really know what the bottleneck is.

**Comment by bmhowe34** [comment]
I'm actually pretty tickled that anybody else had done this. When I did this a few years ago, I wasn't able to find anybody else that had done it, though it looks like you had beaten me to it and I just didn't know it. The fact that we got the same answer makes me pretty happy. Just for grins, I will try to update your code to see if it gets 115.4831 after making the change. I'll keep you posted.

**Comment by bmhowe34** [comment]
> I will try to update your code to see if it gets 115.4831 after making the change. I'll keep you posted.

After updating the code to end the game earlier as described above, your `make create_memory` reported:

> Expected score: 115.483
> 15558063 out of 24971901 (62.3023) not set

This matches what I expected. For clarity, here are the specific changes (not including the updates to the test/long_runners/auto_play*.ans): https://github.com/bmhowe34/qwixxmaster/commit/8fd2347e52d6e0a0227da5d624a1ecce7eeba91d

**Comment by realead** [comment]
Thanks @bmhowe34! Good to know that there was probably only one mistake! Could you please submit a pull request with your changes?

**Comment by realead** [comment]
closed via https://github.com/realead/qwixxmaster/pull/2
